services:
  - type: web
    name: videx
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false
